/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clock;

import static clock.App.TIMER_DEFAULT_VALUE;
import static clock.App.STATUS_OFF;
import static clock.App.STATUS_ON;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class CountdownTimerAcceptanceTests {

	private final ApplicationRunner application = new ApplicationRunner();

	@BeforeEach
	void setupApplication() throws Exception {
		application.setup();
	}

	@Test
	void onceOpenedDisplaysAFrozenCountdownTimerWithDefaultValue() {
		application.launches();
		application.showsCountdownTimerWithDefaultValue(TIMER_DEFAULT_VALUE);
		application.showsCountdownTimerStatus(STATUS_OFF);
	}
	
	@Test
	void launchCountdownTimerAndItStartsDecrementingEverySecond() {
		application.launches();
		application.startsCountdownTimer();
		application.showsCountdownTimerStatus(STATUS_ON);
	}

	@AfterEach
	void closeApplication() throws Exception {
		application.close();
	}

}
