/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clock;

import static clock.ClockApplication.TIMER_INITIAL_VALUE;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

@DisplayName("Countdown Timer Acceptance (End to End) Test Case")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class CountdownTimerAcceptanceTests {

	public static final String STATUS_OFF = "OFF";
	public static final String STATUS_ON = "ON";
	public static final Integer COUNTDOWN_TIMER_STOP_VALUE = 0;
	
	private final ApplicationRunner application = new ApplicationRunner();

	@BeforeEach
	void setupApplication() throws Exception {
		application.setup();
	}

	@Test
	@Order(1)
	void onceOpenedDisplaysAFrozenCountdownTimerWithInitialValue() {
		application.launches();
		application.showsCountdownTimerWithValue(TIMER_INITIAL_VALUE);
		application.showsCountdownTimerStatus(STATUS_OFF);
	}
	
	@Test
	@Order(2)
	void startCountdownTimerAndItUpdatesCountdownTimerStatus() {
		application.launches();
		application.startsCountdownTimer();
		application.showsCountdownTimerStatus(STATUS_ON);
	}
	
	
	@Test
	@Order(3)
	void startCountdownTimerAndItStartsDecrementingEverySecond() throws InterruptedException {
		application.launches();
		application.startsCountdownTimer();
		application.showsCountdownTimerStatus(STATUS_ON);
		application.hasShownCountdownTimerDecrementingEverySecondFor(TIMER_INITIAL_VALUE);
		application.showsCountdownTimerStatus(STATUS_OFF);
		application.showsCountdownTimerWithValue(COUNTDOWN_TIMER_STOP_VALUE);
	}

	@AfterEach
	void closeApplication() throws Exception {
		application.close();
	}

}
